---
title: "Equipo_ZVC_Final"
author: "Zaira V. Avila, Vladimir Espinosa, Claudia Coutiño"
format: html
editor: visual
---

# Descripción de los datos
Para la obtención de la base de datos, se utilizó la plataforma Kaggle...
Base de Datos: "Music & Mental Health Survey Results"

Descripción...

Documentación clara del proceso de descarga. ¿Qué significan las columnas del datasets? Dimensiones del data frame (filas x columnas) ¿Qué tipo de datos analizaste? Describe brevemente el tipo de datos utilizados

☻ ☻ ☻

# Preguntas de Investigación

- Análisis y resultados Analiza los datos y genera 5 preguntas que puedas contestar con las variables que tienes. Genera un reporte completo empleando R Markdown (.Rmd) o Quarto (.qmd) que nos conteste las preguntas realizadas y nos de gráficas de cada uno

- Visualización gráfica La exploración gráfica y la presentación de resultados quedan a tu elección. Sin embargo, deben ser claras y comprensibles para todo público. El reporte será evaluado en función del orden y la coherencia en la presentación de la información, siguiendo una estructura de lo general a lo particular. Debes respetar el orden visto en clase, comenzando con la limpieza y manipulación de datos, y posterior visualización gráfica

**Subir**: Quarto (.qmd), HTML (.html), Figuras
HOLA
